export const TEST_ROW_DATA = [
  {
    name: 'Artistic Creations',
    url: 'https://artisticcreations.test.com',
    author: 'Ethan Brown',
    views: 125,
    comments: 23,
    category: 'Programming',
    created: '05/05/24 10:45',
  },
  {
    name: 'Tech Trends',
    url: 'https://techtrends.test.com',
    author: 'Sophia Johnson',
    views: 89,
    comments: 10,
    category: 'Technology',
    created: '09/08/23 14:20',
  },
  {
    name: 'Home Decor Ideas',
    url: 'https://homedecorideas.test.com',
    author: 'Liam Wilson',
    views: 210,
    comments: 17,
    category: 'Lifestyle',
    created: '12/07/24 11:55',
  },
  {
    name: 'Financial Tips',
    url: 'https://financialtips.test.com',
    author: 'Emma Clark',
    views: 150,
    comments: 35,
    category: 'Finance',
    created: '05/05/24 10:45',
  },
  {
    name: 'Parenting Guide',
    url: 'https://parentingguide.test.com',
    author: 'Noah Perez',
    views: 180,
    comments: 28,
    category: 'Family',
    created: '02/03/24 08:30',
  },
  // Add more random data here
  {
    name: 'Healthy Recipes',
    url: 'https://healthyrecipes.test.com',
    author: 'Chloe Garcia',
    views: 95,
    comments: 14,
    category: 'Food',
    created: '06/11/24 15:40',
  },
  {
    name: 'Outdoor Adventures',
    url: 'https://outdooradventures.test.com',
    author: 'Alexander Hernandez',
    views: 132,
    comments: 20,
    category: 'Travel',
    created: '07/12/24 17:30',
  },
  {
    name: 'Artistic Creations',
    url: 'https://artisticcreations.test.com',
    author: 'Ethan Brown',
    views: 125,
    comments: 23,
    category: 'Programming',
    created: '05/05/24 10:45',
  },
  {
    name: 'Tech Trends',
    url: 'https://techtrends.test.com',
    author: 'Sophia Johnson',
    views: 89,
    comments: 10,
    category: 'Technology',
    created: '09/08/23 14:20',
  },
  {
    name: 'Home Decor Ideas',
    url: 'https://homedecorideas.test.com',
    author: 'Liam Wilson',
    views: 210,
    comments: 17,
    category: 'Lifestyle',
    created: '12/07/24 11:55',
  },
  {
    name: 'Financial Tips',
    url: 'https://financialtips.test.com',
    author: 'Emma Clark',
    views: 150,
    comments: 35,
    category: 'Finance',
    created: '05/05/24 10:45',
  },
  {
    name: 'Parenting Guide',
    url: 'https://parentingguide.test.com',
    author: 'Noah Perez',
    views: 180,
    comments: 28,
    category: 'Family',
    created: '02/03/24 08:30',
  },
  // Add more random data here
  {
    name: 'Healthy Recipes',
    url: 'https://healthyrecipes.test.com',
    author: 'Chloe Garcia',
    views: 95,
    comments: 14,
    category: 'Food',
    created: '06/11/24 15:40',
  },
  {
    name: 'Outdoor Adventures',
    url: 'https://outdooradventures.test.com',
    author: 'Alexander Hernandez',
    views: 132,
    comments: 20,
    category: 'Travel',
    created: '07/12/24 17:30',
  },
  {
    name: 'Artistic Creations',
    url: 'https://artisticcreations.test.com',
    author: 'Ethan Brown',
    views: 125,
    comments: 23,
    category: 'Programming',
    created: '05/05/24 10:45',
  },
  {
    name: 'Tech Trends',
    url: 'https://techtrends.test.com',
    author: 'Sophia Johnson',
    views: 89,
    comments: 10,
    category: 'Technology',
    created: '09/08/23 14:20',
  },
  {
    name: 'Home Decor Ideas',
    url: 'https://homedecorideas.test.com',
    author: 'Liam Wilson',
    views: 210,
    comments: 17,
    category: 'Lifestyle',
    created: '12/07/24 11:55',
  },
  {
    name: 'Financial Tips',
    url: 'https://financialtips.test.com',
    author: 'Emma Clark',
    views: 150,
    comments: 35,
    category: 'Finance',
    created: '05/05/24 10:45',
  },
  {
    name: 'Parenting Guide',
    url: 'https://parentingguide.test.com',
    author: 'Noah Perez',
    views: 180,
    comments: 28,
    category: 'Family',
    created: '02/03/24 08:30',
  },
  // Add more random data here
  {
    name: 'Healthy Recipes',
    url: 'https://healthyrecipes.test.com',
    author: 'Chloe Garcia',
    views: 95,
    comments: 14,
    category: 'Food',
    created: '06/11/24 15:40',
  },
  {
    name: 'Outdoor Adventures',
    url: 'https://outdooradventures.test.com',
    author: 'Alexander Hernandez',
    views: 132,
    comments: 20,
    category: 'Travel',
    created: '07/12/24 17:30',
  },
]
